In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import mean_squared_error


In [2]:
boston=pd.read_csv('boston_house_prices.csv',sep=',')

In [3]:
# Visualisation des données
print(boston.shape)
print(boston.head(3))

(506, 14)
      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  


In [4]:
# y (target) : MEDV (dernière colonne) median value of owner-occupied homes in \$1000s.
# X (données) : CRIM, ZN, INDUS, CHAS, NOX, RM, AGE, DIS, RAD, TAX, PTRATIO, B, LSTAT (13 col)

# calcul des correlation entre y et chacun des x :
for col in boston.columns :
	print(col, boston[col].corr(boston['MEDV']))


CRIM -0.38830460858681154
ZN 0.3604453424505432
INDUS -0.4837251600283729
CHAS 0.17526017719029843
NOX -0.4273207723732826
RM 0.6953599470715393
AGE -0.3769545650045963
DIS 0.24992873408590388
RAD -0.381626230639778
TAX -0.4685359335677669
PTRATIO -0.5077866855375621
B 0.33346081965706637
LSTAT -0.7376627261740151
MEDV 1.0


In [6]:
boston2 = boston[['CRIM', 'ZN', 'INDUS', 'NOX', 'RM', 'RAD', 'DIS', 'PTRATIO',  'LSTAT', 'MEDV']]

y = boston2.iloc[:,-1:].values
x = boston2.iloc[:,:-1].values
print(x.shape, y.shape) # 

X = np.hstack((x, np.ones(y.shape)))

theta = np.random.randn(10,1)
print(theta)
m = boston2.shape[0]

print(X.shape, y.shape, theta.shape, m) # (506, 10) (506, 1) (10, 1) 506




(506, 9) (506, 1)
[[ 0.21195187]
 [-0.19931651]
 [-0.21255282]
 [-0.27458154]
 [-0.06582927]
 [-2.03011356]
 [-1.3924496 ]
 [ 0.86494207]
 [ 1.3997611 ]
 [-1.20106397]]
(506, 10) (506, 1) (10, 1) 506


In [7]:
# Création du modèle (model(X,theta)) 

def modelmult(X, theta):
	return X.dot(theta)
# Fonction du coût (fonction_cout(X,y,theta))

def fonction_cout(X, y, theta):
	return 1/(2*m) * np.sum((modelmult(X, theta) - y)**2)

# Le gradient (gradient(X,y,theta))

def gradient(X,y,theta):
	return 1/m * X.T.dot(modelmult(X, theta) - y)
print(gradient(X, y, theta))
# Descente du gradient (descente_gradient(X,y,theta,alpha,n_iterations))

def descente_gradient(X,y,theta,alpha,n_iterations):
	for i in range(n_iterations): 
		theta = theta - alpha*gradient(X, y, theta)
	return theta



[[ -61.65831764]
 [-423.61805823]
 [-182.48721733]
 [ -10.20443505]
 [-128.42744394]
 [-228.60464829]
 [ -82.44173493]
 [-343.82828547]
 [-155.66580417]
 [ -19.16266632]]


In [8]:
theta1 = descente_gradient(X, y, theta, 0.001, 5000)
theta2 = descente_gradient(X, y, theta, 0.0005, 3300)
theta3 = descente_gradient(X, y, theta, 0.002, 1500)

print(theta1, fonction_cout(X, y, theta1)) # 13.196
print(theta2, fonction_cout(X, y, theta2)) # 14.115
print(theta3, fonction_cout(X, y, theta3)) # 1050815795310118.4

print(mean_squared_error(y, modelmult(X, theta1))) # 26.460
print(mean_squared_error(y, modelmult(X, theta2))) # 28.035
print(mean_squared_error(y, modelmult(X, theta3))) # 7594507303458618.0



[[-0.11873478]
 [ 0.04437746]
 [-0.09048748]
 [ 0.04319869]
 [ 6.09947317]
 [-0.02248495]
 [-0.88122477]
 [-0.27892771]
 [-0.46910021]
 [-0.32849668]] 13.362093498271667
[[-0.1252356 ]
 [ 0.07342601]
 [-0.08767312]
 [-0.00949529]
 [ 4.74582806]
 [-0.0550598 ]
 [-1.02276724]
 [ 0.28300324]
 [-0.55285034]
 [-0.68460392]] 14.430468086589796
[[ -792819.63081505]
 [-3383857.34961022]
 [-1999477.3961496 ]
 [ -100231.73531581]
 [-1147420.91655573]
 [-1867663.53097042]
 [ -741552.35529703]
 [-3357210.97830254]
 [-2341332.07853732]
 [ -182286.41023562]] 1.9216774248348476e+16
26.724186996543338
28.860936173179596
3.843354849669695e+16
